import { Player, PaymentRecord, Match, GalleryPhoto, GalleryAlbum, Sponsor, SystemSettings, AudioNote, PlayerCategory } from "@/types";

export const INITIAL_SETTINGS: SystemSettings = {
  academyName: "Golden Sport Academy Santa Cruz",
  sinpePhone: "62806989",
  coachPhone: "62806989",
  sinpeOwner: "Yorleny Monge Soto (BAC / Sinpe Móvil)",
  ibanAccount: "CR80015202001388847473",
  bankName: "Banco de Costa Rica (BCR - MONGE SOTO YORLENY PATRICIA)",
  monthlyFeeDefault: 10000,
  adminPin: "20261829",
  brandStudio: "Curiol Studio",
  arbolGuanacasteUrl: "https://www.curiol.studio/linea-de-tiempo/golden-academy-santa-cruz",
  address: "Santa Bárbara de Santa Cruz, Guanacaste, Costa Rica",
};

export const INITIAL_CATEGORIES: string[] = [
  "Iniciación / Menores de U8 (U6-U8)",
  "Mini-Básquet (U8-U10)",
  "Infantil (U12-U14)",
  "Juvenil (U16-U18)",
  "Clínicas de Tecnificación & Tiro",
  "Intercantonal",
  "Eventos Especiales",
  "Presentación de Uniformes"
];

export const INITIAL_PLAYERS: Player[] = [
  {
    id: "ply-test-alberto",
    fullName: "Mateo Bustos (Prueba Oficial)",
    birthDate: "2015-06-18",
    age: "11 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Alberto Bustos",
    guardianPhone: "60602617",
    guardianEmail: "alberto.bustos.ortega@mep.go.cr",
    address: "Santa Cruz Centro, Guanacaste",
    school: "Escuela Santa Cruz",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y pruebas de sistema",
    jerseyNumber: 18,
    position: "Alero",
    tshirtSize: "12",
    bloodType: "O+",
    dominantHand: "Diestro",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "pendiente",
    isActive: true,
  },
  {
    id: "ply-001",
    fullName: "Kendal Josué Cubillo Moreno",
    birthDate: "24-06-2014",
    age: "12 años ,3 meses",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Wendy Moreno Moreno",
    guardianPhone: "83167302",
    address: "125 metros Sur de los Tribunales de Justicia; Santa Cruz Centro.",
    school: "Centro Educativo Espíritu Santo",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 1,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-002",
    fullName: "Analía Sánchez Cruz",
    birthDate: "25/04/2014",
    age: "12 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Ana Lorena Cruz / Yanory Cruz",
    guardianPhone: "60756971 Madre 85938151 Tía",
    address: "De la iglesia católica de Santa Barbara 200mtrs noreste",
    school: "Escuela Guaitil",
    medicalNotes: "Grcs a Dios hasta el momento  Sana",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 2,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-003",
    fullName: "Skyla Chaves Gutierrez",
    birthDate: "24 enero 2018",
    age: "8 años",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Alexandra Gutierrez Achio",
    guardianPhone: "8493 65 22",
    address: "Barrio corobici 2 diagonal al medico cubano",
    school: "Escuela josefina lopez bonilla",
    medicalNotes: "NA",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 3,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-004",
    fullName: "Helena Matarrita Villafuerte",
    birthDate: "22-01-2014",
    age: "12 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Hellen Villafuerte Camareno",
    guardianPhone: "8425-0335",
    address: "Costado Este de la Plaza de deportes de Guaitil",
    school: "Escuela Guaitil",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 4,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-005",
    fullName: "Alayne Olmazo Serrano",
    birthDate: "03/06/2015",
    age: "11 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "María José Olmazo Serrano",
    guardianPhone: "63439638",
    address: "De la plaza de Polvazal 100metros este casa color Amarillo",
    school: "Escuela Modelo talolinguita",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 5,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-006",
    fullName: "Carlos Arturo olmazo serrano",
    birthDate: "17/01/2016",
    age: "10",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Ana lucia olmazo serrano",
    guardianPhone: "61515521",
    address: "De la plaza de polvazal 100este casa color amarillo",
    school: "Escuela María marín galagarza",
    medicalNotes: "Ninguna gracias a Dios",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 6,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-007",
    fullName: "David Galagarza Villarreal",
    birthDate: "14/09/2015",
    age: "10",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Anlly Villarreal Guevara",
    guardianPhone: "85268979",
    address: "200m Sur del CTP Santa Bárbara c",
    school: "Escuela María Marín Galagarza",
    medicalNotes: "asmático y alérgico  tratado",
    photoAuthorized: false,
    photoAuthNotes: "PROHIBIDO: Sin autorización de imagen para fotos/videos en redes sociales",
    jerseyNumber: 7,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-008",
    fullName: "Britney tatiana Vega Rosricuez",
    birthDate: "13 /6 /2014",
    age: "12 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Angel Agustin Vega Guido",
    guardianPhone: "64 41 73 09",
    address: "Lomachata  proyecto alamo casa  #58",
    school: "Escuela de Guaitil",
    medicalNotes: "Asma",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 8,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-009",
    fullName: "Maria Belen Villegas Alcocer",
    birthDate: "14 de enero 2016",
    age: "10 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Alfredo Villegas Vilchez",
    guardianPhone: "85384739",
    address: "Santa Barbara de Santa Cruz, diagonal a la Escuela Maia Marn Galagarza",
    school: "Escuela Maria Marin Galagarza",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 9,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-010",
    fullName: "Emiliano Baltodano Oquendo",
    birthDate: "04/8/2015",
    age: "11",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Cindya Oquendo Gutiérrez",
    guardianPhone: "83290227",
    address: "ORIENTE Santa Bárbara",
    school: "Escuela María Marín Galagarza",
    medicalNotes: "Migraña yAsma",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 10,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-011",
    fullName: "Emiliano Barrantes Villafuerte",
    birthDate: "01-03-2015",
    age: "11",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Lisdiana Villafuerte Chavarria",
    guardianPhone: "64604725.            84465592",
    address: "Guaiti Loma Chata, del Residencial Alamo 1 k sur",
    school: "Escuela Guaitil",
    medicalNotes: "Niega",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 11,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-012",
    fullName: "Dariel GUADAMUZ Alcocer",
    birthDate: "11/10/2017",
    age: "8",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Ariel GUADAMUZ Villafuerte",
    guardianPhone: "60158751",
    address: "Dela plaza de deportes de polvazales 100 al este",
    school: "Amaranta",
    medicalNotes: "Nada",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 12,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-013",
    fullName: "Jhoan David Ramírez Ramírez",
    birthDate: "20 Setiembre 2017",
    age: "8 años",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Liseth Ramírez Vallejos",
    guardianPhone: "86466594",
    address: "Santa Bárbara",
    school: "Esc María Marín Galagarza",
    medicalNotes: "Alérgico a la Acetaminofen",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 13,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-014",
    fullName: "Emily Bustos Monge",
    birthDate: "17/04/2014",
    age: "12",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Yorleny Monge Soto",
    guardianPhone: "62806989",
    address: "Santa Bárbara",
    school: "Escuela Guaitil",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 14,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-015",
    fullName: "Lucía Villafuerte Villafuerte",
    birthDate: "24-3-2015",
    age: "11 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Katy Villafuerte Mayorga",
    guardianPhone: "70260472",
    address: "400 mts al noroeste de la plaza de deportes Guaitil.",
    school: "Escuela Guaitil",
    medicalNotes: "Sin pedecimientos.",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 15,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-016",
    fullName: "Dariela Jaén Moreno",
    birthDate: "17/12/2015",
    age: "10 años y 8 meses",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Ariana Marcela Moreno Moreno",
    guardianPhone: "88 97 66 10",
    address: "Oriente Santa Barbara",
    school: "Espíritu Santo",
    medicalNotes: "Asma",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 16,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-017",
    fullName: "Lucía Padilla Gutiérrez",
    birthDate: "17 Julio 2018",
    age: "8 años",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Yajaira Gutiérrez Chaves",
    guardianPhone: "88123339",
    address: "Santa Bárbara",
    school: "CEEES",
    medicalNotes: "Asma",
    photoAuthorized: false,
    photoAuthNotes: "PROHIBIDO: Sin autorización de imagen para fotos/videos en redes sociales",
    jerseyNumber: 17,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-018",
    fullName: "Delia Alanna Grijalba Ramirez",
    birthDate: "25 012017",
    age: "9",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Karolina Ramirez Ramirez",
    guardianPhone: "88 99 45 02",
    address: "500 norte de la virgen de los Ángeles coope Espavelar primera entrada quinta casa a mano derecha",
    school: "Espíritu Santo",
    medicalNotes: "Ninguna",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 18,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-019",
    fullName: "Isabella Villafuerte Villafuerte",
    birthDate: "7/10/2020",
    age: "5 años",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Katy Villafuerte Mayorga",
    guardianPhone: "70260472",
    address: "400 mts al noroeste de la plaza de deportes Guaitil.",
    school: "Escuela Guaitil",
    medicalNotes: "No presenta.",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 19,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-020",
    fullName: "Sebastian Martinez Viales",
    birthDate: "22 de Enero del 2014",
    age: "12 años",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Cindy Maria Viales Perez",
    guardianPhone: "61-84-33-84 /87-62-25-78",
    address: "Del colegio de Santa Barbara 200metros al oeste y 125 sur",
    school: "Guaitil",
    medicalNotes: "No",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 20,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-021",
    fullName: "Isabella Monge Jiménez",
    birthDate: "13 febrero 2012",
    age: "14 años",
    category: "Pasarela Mixto / U14-U16",
    guardianName: "Bryan Monge/ Cindy Jiménez",
    guardianPhone: "86774242. / 87701717",
    address: "San Vicente , Nicoya Guanacaste",
    school: "Colegio CTP Santa Bárbara",
    medicalNotes: "Ninguna / aplicable",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 21,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-022",
    fullName: "Alex Snayder Padilla Cubillo",
    birthDate: "17 de enero 2015",
    age: "11",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Dayana Cubillo Hernández",
    guardianPhone: "62231082",
    address: "Del CTP de Santa Bárbara 500mts al sur oeste",
    school: "Escuela De Guaitil",
    medicalNotes: "No",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 22,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-023",
    fullName: "Elena Marchena Alcocer",
    birthDate: "1 de noviembre del 2010",
    age: "15",
    category: "Pasarela Mixto / U14-U16",
    guardianName: "Yanina Alcocer Peralta",
    guardianPhone: "+506 7090 6841",
    address: "Santa Bárbara",
    school: "Centro educativo estudiantil Espíritu Santo",
    medicalNotes: "Nada",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 23,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-024",
    fullName: "Mariana Gómez Arrieta",
    birthDate: "21/12/2016",
    age: "9",
    category: "Mini-Baloncesto Mixto / U10-U12",
    guardianName: "Cristina Arrieta Chavarría",
    guardianPhone: "88980469",
    address: "De la entrada principal a Santa Bárbara, 100 metros suroeste",
    school: "Escuela María Marín Galagarza",
    medicalNotes: "Sin detalle",
    photoAuthorized: true,
    photoAuthNotes: "Autorizado para difusión y redes sociales",
    jerseyNumber: 24,
    position: "Formativo",
    registrationDate: "2026-08-29",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: "pay-test-alberto",
    playerId: "ply-test-alberto",
    playerName: "Mateo Bustos (Prueba Oficial)",
    guardianName: "Alberto Bustos",
    guardianPhone: "60602617",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-001",
    playerId: "ply-001",
    playerName: "Kendal Josué Cubillo Moreno",
    guardianName: "Wendy Moreno Moreno",
    guardianPhone: "83167302",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202601",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-002",
    playerId: "ply-002",
    playerName: "Analía Sánchez Cruz",
    guardianName: "Ana Lorena Cruz / Yanory Cruz",
    guardianPhone: "60756971 Madre 85938151 Tía",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202602",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-003",
    playerId: "ply-003",
    playerName: "Skyla Chaves Gutierrez",
    guardianName: "Alexandra Gutierrez Achio",
    guardianPhone: "8493 65 22",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202603",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-004",
    playerId: "ply-004",
    playerName: "Helena Matarrita Villafuerte",
    guardianName: "Hellen Villafuerte Camareno",
    guardianPhone: "8425-0335",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-005",
    playerId: "ply-005",
    playerName: "Alayne Olmazo Serrano",
    guardianName: "María José Olmazo Serrano",
    guardianPhone: "63439638",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202605",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-006",
    playerId: "ply-006",
    playerName: "Carlos Arturo olmazo serrano",
    guardianName: "Ana lucia olmazo serrano",
    guardianPhone: "61515521",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202606",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-007",
    playerId: "ply-007",
    playerName: "David Galagarza Villarreal",
    guardianName: "Anlly Villarreal Guevara",
    guardianPhone: "85268979",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-008",
    playerId: "ply-008",
    playerName: "Britney tatiana Vega Rosricuez",
    guardianName: "Angel Agustin Vega Guido",
    guardianPhone: "64 41 73 09",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202608",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-009",
    playerId: "ply-009",
    playerName: "Maria Belen Villegas Alcocer",
    guardianName: "Alfredo Villegas Vilchez",
    guardianPhone: "85384739",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202609",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-010",
    playerId: "ply-010",
    playerName: "Emiliano Baltodano Oquendo",
    guardianName: "Cindya Oquendo Gutiérrez",
    guardianPhone: "83290227",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202610",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-011",
    playerId: "ply-011",
    playerName: "Emiliano Barrantes Villafuerte",
    guardianName: "Lisdiana Villafuerte Chavarria",
    guardianPhone: "64604725.            84465592",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-012",
    playerId: "ply-012",
    playerName: "Dariel GUADAMUZ Alcocer",
    guardianName: "Ariel GUADAMUZ Villafuerte",
    guardianPhone: "60158751",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202612",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-013",
    playerId: "ply-013",
    playerName: "Jhoan David Ramírez Ramírez",
    guardianName: "Liseth Ramírez Vallejos",
    guardianPhone: "86466594",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202613",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-014",
    playerId: "ply-014",
    playerName: "Emily Bustos Monge",
    guardianName: "Yorleny Monge Soto",
    guardianPhone: "62806989",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202614",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-015",
    playerId: "ply-015",
    playerName: "Lucía Villafuerte Villafuerte",
    guardianName: "Katy Villafuerte Mayorga",
    guardianPhone: "70260472",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202615",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-016",
    playerId: "ply-016",
    playerName: "Dariela Jaén Moreno",
    guardianName: "Ariana Marcela Moreno Moreno",
    guardianPhone: "88 97 66 10",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-017",
    playerId: "ply-017",
    playerName: "Lucía Padilla Gutiérrez",
    guardianName: "Yajaira Gutiérrez Chaves",
    guardianPhone: "88123339",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202617",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-018",
    playerId: "ply-018",
    playerName: "Delia Alanna Grijalba Ramirez",
    guardianName: "Karolina Ramirez Ramirez",
    guardianPhone: "88 99 45 02",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "atrasado",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-019",
    playerId: "ply-019",
    playerName: "Isabella Villafuerte Villafuerte",
    guardianName: "Katy Villafuerte Mayorga",
    guardianPhone: "70260472",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202619",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-020",
    playerId: "ply-020",
    playerName: "Sebastian Martinez Viales",
    guardianName: "Cindy Maria Viales Perez",
    guardianPhone: "61-84-33-84 /87-62-25-78",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-sep-021",
    playerId: "ply-021",
    playerName: "Isabella Monge Jiménez",
    guardianName: "Bryan Monge/ Cindy Jiménez",
    guardianPhone: "86774242. / 87701717",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202621",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-022",
    playerId: "ply-022",
    playerName: "Alex Snayder Padilla Cubillo",
    guardianName: "Dayana Cubillo Hernández",
    guardianPhone: "62231082",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202622",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-023",
    playerId: "ply-023",
    playerName: "Elena Marchena Alcocer",
    guardianName: "Yanina Alcocer Peralta",
    guardianPhone: "+506 7090 6841",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202623",
    paymentDate: "2026-09-02",
  },
  {
    id: "pay-sep-024",
    playerId: "ply-024",
    playerName: "Mariana Gómez Arrieta",
    guardianName: "Cristina Arrieta Chavarría",
    guardianPhone: "88980469",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    dueDate: "2026-09-12",
    sinpeReference: "SINPE-202624",
    paymentDate: "2026-09-02",
  },
];

// CARTELERA OFICIAL DE PARTIDOS DEL SÁBADO 5 DE SEPTIEMBRE EN LIBERIA
export const INITIAL_MATCHES: Match[] = [
  {
    id: "mtc-lib-2",
    category: "Mini-Básquet (U8-U10)",
    opponent: "Parajeles",
    matchDate: "2026-09-05",
    matchTime: "09:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles en categoría U10.",
  },
  {
    id: "mtc-lib-3",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles (U12 Mixto)",
    matchDate: "2026-09-05",
    matchTime: "10:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles (U12 Mixto).",
  },
  {
    id: "mtc-lib-4",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles (U14 Masc)",
    matchDate: "2026-09-05",
    matchTime: "11:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles (U14 Masculino).",
  },
  {
    id: "mtc-lib-5",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles",
    matchDate: "2026-09-05",
    matchTime: "12:00 MD",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Santa Cruz vs Parajeles en U12 Mixto ⭐",
  },
  {
    id: "mtc-lib-6",
    category: "Infantil (U12-U14)",
    opponent: "Golden Sport Academy Santa Cruz (Fem)",
    matchDate: "2026-09-05",
    matchTime: "01:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Golden Sport Academy Santa Cruz (U12 Femenino) ⭐",
  },
  {
    id: "mtc-lib-7",
    category: "Infantil (U12-U14)",
    opponent: "Golden Sport Academy Santa Cruz (Mixto)",
    matchDate: "2026-09-05",
    matchTime: "02:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Golden Sport Academy Santa Cruz (U12 Mixto) ⭐",
  }
];

export const INITIAL_ALBUMS: GalleryAlbum[] = [
  {
    id: "alb-comunidad-liberia-2026",
    title: "Álbum Familiar • Gran Jornada de Liberia",
    eventDate: "2026-09-05",
    category: "Intercantonal",
    coverPhotoUrl: "/Hero_Basketball/1.jpg",
    createdBy: "Familias & Papás",
    albumType: "community",
    isLocked: false,
    isOpenForUploads: true,
  },
  {
    id: "alb-curiol-liberia-2026",
    title: "Galería Oficial Curiol Studio • Gran Jornada de Liberia 2026",
    eventDate: "2026-09-05",
    category: "Intercantonal",
    coverPhotoUrl: "/Hero_Basketball/2.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: false,
    isOpenForUploads: true,
  },
  {
    id: "alb-2",
    title: "Presentación del Uniforme Oficial",
    eventDate: "2026-08-22",
    category: "Presentación de Uniformes",
    coverPhotoUrl: "/photos/uniforme/GoldenAcademy_StaCruz_001.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: true,
    isOpenForUploads: false,
  },
  {
    id: "alb-3",
    title: "Clínicas de Tecnificación & Tiro",
    eventDate: "2026-08-20",
    category: "Clínicas de Tecnificación & Tiro",
    coverPhotoUrl: "/Hero_Basketball/2.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: true,
    isOpenForUploads: false,
  }
];

export const INITIAL_PHOTOS: GalleryPhoto[] = [
  // FOTOGRAFÍAS OFICIALES CURIOL STUDIO - PRESENTACIÓN DEL UNIFORME OFICIAL (16 FOTOS, alb-2)
  ...[
    "001", "002", "003", "004", "005", "006", "007", "008",
    "009", "010", "011", "012", "013", "014", "015", "016"
  ].map((num, idx) => ({
    id: `pht-uni-${num}`,
    photoUrl: `/photos/uniforme/GoldenAcademy_StaCruz_${num}.jpg`,
    title: `Presentación Oficial • Atleta #${num}`,
    caption: `Sesión fotográfica oficial de gala para la presentación de indumentaria deportiva de Golden Sport Academy Santa Cruz.`,
    category: "Presentación de Uniformes" as PlayerCategory,
    uploaderName: "Curiol Studio Oficial",
    uploaderRole: "staff" as const,
    photoType: "pro_studio" as const,
    albumId: "alb-2",
    eventDate: "2026-08-22",
    likesCount: 15 + (idx % 12),
    isApproved: true,
    uploadedAt: "2026-08-22",
    watermarkTag: "Curiol Studio Santa Cruz",
    priceDigital: 2500,
    pricePrint: 3500,
  }))
];

export const INITIAL_GALLERY_PHOTOS = INITIAL_PHOTOS;

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: "spn-1",
    name: "Curiol Studio",
    logoUrl: "/curiol-studio-logo.png",
    tier: "oro",
    websiteUrl: "https://www.curiol.studio",
    phone: "62806989",
    contactName: "Jenny Briceño",
    isActive: true,
  }
];

export const INITIAL_AUDIO_NOTES: AudioNote[] = [
  {
    id: "aud-1",
    title: "Coordinación logística para la jornada en Liberia",
    transcript: "Organizar la salida de los atletas a las 6:30 AM desde Santa Bárbara. Llevar hidratación y los uniformes dorados oficiales.",
    summaryIA: "Salida 6:30 AM hacia el Gimnasio Municipal de Liberia. Uniforme de gala y botiquín listo.",
    actionItems: [
      "Confirmar transporte de los niños",
      "Revisión de balones y uniformes",
      "Puntualidad en el primer partido de las 8:00 AM"
    ],
    category: "directiva",
    recordedAt: "2026-09-03",
    author: "Coach Lenny Monge",
  }
];
