import { AcademySettings, GalleryAlbum, GalleryPhoto, Match, PaymentRecord, Player, Sponsor } from '../types';

export const INITIAL_SETTINGS: AcademySettings = {
  name: "Golden Sport Academy Santa Cruz",
  brandStudio: "Curiol Studio",
  locationName: "Cancha de Básquetbol de Santa Bárbara",
  address: "Santa Bárbara, Santa Cruz, Guanacaste, Costa Rica",
  venueNote: "Sede principal en Santa Bárbara de Santa Cruz (las canchas y sedes pueden coordinarse según el torneo o partido oficial).",
  wazeUrl: "https://waze.com/ul?q=Santa+Barbara+Santa+Cruz+Guanacaste",
  googleMapsUrl: "https://maps.google.com/?q=Santa+Barbara+Santa+Cruz+Guanacaste",
  sinpePhone: "62806989",
  sinpeOwner: "Golden Sport Academy / Curiol Studio",
  ibanAccount: "CR45015100010012345678",
  bankName: "Banco Nacional de Costa Rica",
  contactPhone: "+506 6280-6989",
  contactEmail: "contacto@goldensportacademy.com",
  instagramUrl: "https://instagram.com/goldensportacademy",
  facebookUrl: "https://facebook.com/goldensportacademy",
  defaultMonthlyFee: 18000,
  defaultDueDay: 5,
};

export const INITIAL_PLAYERS: Player[] = [
  {
    id: "ply-1",
    firstName: "Thiago",
    lastName: "Pérez Briceño",
    birthDate: "2019-03-12",
    category: "Iniciación / Menores de U8 (U6-U8)",
    jerseyNumber: 3,
    position: "Iniciación",
    medicalNotes: "Sin alergias. Excelente energía y coordinación.",
    guardianName: "Yorleny (Lenny) Monge Soto",
    guardianPhone: "62806989",
    guardianEmail: "lenny.monge@goldensportacademy.com",
    monthlyFee: 18000,
    dueDay: 5,
    isActive: true,
    photoUrl: "/Fotos_Equipo/1.jpg",
    createdAt: "2026-02-01",
  },
  {
    id: "ply-2",
    firstName: "Kendall",
    lastName: "Alvarado Leal",
    birthDate: "2016-07-15",
    category: "Mini-Básquet (U8-U10)",
    jerseyNumber: 10,
    position: "Formativo",
    medicalNotes: "Ninguna condición médica.",
    guardianName: "Jorge Alvarado",
    guardianPhone: "83344556",
    guardianEmail: "jorge.alv@gmail.com",
    monthlyFee: 18000,
    dueDay: 5,
    isActive: true,
    photoUrl: "/Fotos_Equipo/2.jpg",
    createdAt: "2026-01-20",
  },
  {
    id: "ply-3",
    firstName: "Mateo",
    lastName: "Gutiérrez Vega",
    birthDate: "2013-04-14",
    category: "Infantil (U12-U14)",
    jerseyNumber: 7,
    position: "Base (PG)",
    medicalNotes: "Apto para alta competencia.",
    guardianName: "Carlos Gutiérrez",
    guardianPhone: "87654321",
    guardianEmail: "cgutierrez@gmail.com",
    monthlyFee: 18000,
    dueDay: 5,
    isActive: true,
    photoUrl: "/Fotos_Equipo/3.jpg",
    createdAt: "2026-01-15",
  },
  {
    id: "ply-4",
    firstName: "Sebastián",
    lastName: "Ríos Mendoza",
    birthDate: "2010-08-20",
    category: "Juvenil (U16-U18)",
    jerseyNumber: 23,
    position: "Escolta (SG)",
    medicalNotes: "Usa rodillera preventiva izquierda.",
    guardianName: "Mariana Mendoza",
    guardianPhone: "89123456",
    guardianEmail: "mariana.mendoza@yahoo.com",
    monthlyFee: 18000,
    dueDay: 5,
    isActive: true,
    photoUrl: "/Fotos_Equipo/4.jpg",
    createdAt: "2026-01-18",
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: "pay-1",
    playerId: "ply-1",
    playerName: "Thiago Pérez Briceño",
    guardianName: "Yorleny (Lenny) Monge Soto",
    guardianPhone: "62806989",
    month: "Septiembre 2026",
    monthIndex: 9,
    year: 2026,
    amount: 18000,
    status: "paid",
    dueDate: "2026-09-05",
    paidDate: "2026-09-02",
    paymentMethod: "Sinpe Móvil",
    notes: "Comprobante Sinpe verificado",
  }
];

// JORNADA DE PARTIDOS OFICIAL (5 DE SEPTIEMBRE - GIMNASIO MUNICIPAL DE LIBERIA)
export const INITIAL_MATCHES: Match[] = [
  {
    id: "mtc-lib-1",
    opponent: "Golden Sport Liberia",
    opponentLogo: "🏀",
    category: "Iniciación / Menores de U8 (U6-U8)",
    matchDate: "2026-09-05",
    matchTime: "08:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Jornada Formativa U8. Inauguración del encuentro en el Gimnasio Municipal de Liberia. ¡Entrada Gratuita!",
  },
  {
    id: "mtc-lib-2",
    opponent: "Parajeles",
    opponentLogo: "⚡",
    category: "Mini-Básquet (U8-U10)",
    matchDate: "2026-09-05",
    matchTime: "09:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Partido categoría U10: Golden Sport vs Parajeles.",
  },
  {
    id: "mtc-lib-3",
    opponent: "Parajeles",
    opponentLogo: "⚡",
    category: "Infantil (U12-U14)",
    matchDate: "2026-09-05",
    matchTime: "10:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Partido categoría U12 Mixto: Golden Sport vs Parajeles.",
  },
  {
    id: "mtc-lib-4",
    opponent: "Parajeles",
    opponentLogo: "⚡",
    category: "Infantil (U12-U14)",
    matchDate: "2026-09-05",
    matchTime: "11:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Partido categoría U14 Masculino: Golden Sport vs Parajeles.",
  },
  {
    id: "mtc-lib-5",
    opponent: "Parajeles",
    opponentLogo: "⚡",
    category: "Infantil (U12-U14)",
    matchDate: "2026-09-05",
    matchTime: "12:00 MD",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Partido categoría U12 Mixto: Golden Santa Cruz vs Parajeles.",
  },
  {
    id: "mtc-lib-6",
    opponent: "Golden Sport Liberia",
    opponentLogo: "🏀",
    category: "Infantil (U12-U14)",
    matchDate: "2026-09-05",
    matchTime: "01:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Partido categoría U12 Femenino: Golden Liberia vs Golden Santa Cruz.",
  },
  {
    id: "mtc-lib-7",
    opponent: "Golden Sport Liberia",
    opponentLogo: "🏀",
    category: "Infantil (U12-U14)",
    matchDate: "2026-09-05",
    matchTime: "02:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    homeAway: "visita",
    status: "upcoming",
    summary: "Gran Cierre de Jornada U12 Mixto: Golden Liberia vs Golden Santa Cruz. ¡El baloncesto nos une!",
  }
];

export const INITIAL_ALBUMS: GalleryAlbum[] = [
  {
    id: "alb-1",
    title: "Jornada de Partidos - Gimnasio Municipal de Liberia",
    eventDate: "2026-09-05",
    category: "General",
    description: "Cobertura oficial y recuerdos de la jornada intercantonal en Liberia.",
    createdBy: "Curiol Studio",
    isOpenForUploads: true,
    coverPhotoUrl: "/partidos/IMG-20260827-WA0018.jpg",
  }
];

export const INITIAL_GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "gal-pro-1",
    albumId: "alb-1",
    eventDate: "2026-09-05",
    title: "Afiche Oficial - Jornada de Partidos 5 de Septiembre",
    category: "General",
    photoUrl: "/partidos/IMG-20260827-WA0018.jpg",
    caption: "Programación oficial de encuentros en el Gimnasio Municipal de Liberia. ¡El baloncesto nos une! Entrada gratuita.",
    uploaderName: "Curiol Studio Oficial",
    isApproved: true,
    likesCount: 95,
    createdAt: "2026-09-03T18:30:00Z",
    photoType: "pro_studio",
    watermarkTag: "Curiol Studio Santa Cruz",
  },
  {
    id: "gal-pro-2",
    albumId: "alb-1",
    eventDate: "2026-09-03",
    title: "Atleta Formativo Golden Sport #1",
    category: "Iniciación / Menores de U8 (U6-U8)",
    photoUrl: "/Fotos_Equipo/1.jpg",
    caption: "Retrato oficial con balón en mano y uniforme de juego.",
    uploaderName: "Curiol Studio Oficial",
    isApproved: true,
    likesCount: 68,
    createdAt: "2026-09-03T12:00:00Z",
    photoType: "pro_studio",
    watermarkTag: "Curiol Studio Santa Cruz",
  }
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: "spn-1",
    name: "Curiol Studio Fotográfico & Recuerdos",
    tier: "oro",
    logoUrl: "/logo.png",
    tagline: "Patrocinador Oficial & Cobertura Gráfica. Retratos para neveras, retablos de madera, canvas y torneos.",
    websiteUrl: "https://goldensportacademy.com/galeria",
    whatsappPhone: "50662806989",
    isActive: true,
    orderIndex: 1,
  }
];
