import { Player, PaymentRecord, Match, GalleryPhoto, GalleryAlbum, Sponsor, SystemSettings, AudioNote, PlayerCategory } from "@/types";

export const INITIAL_SETTINGS: SystemSettings = {
  academyName: "Golden Sport Academy Santa Cruz",
  sinpePhone: "62806989",
  coachPhone: "62806989",
  sinpeOwner: "Yorleny Monge Soto (BAC / Sinpe Móvil)",
  ibanAccount: "CR80015202001388847473",
  bankName: "Banco de Costa Rica (BCR - MONGE SOTO YORLENY PATRICIA)",
  monthlyFeeDefault: 10000,
  adminPin: "20261829",
  brandStudio: "Curiol Studio",
  arbolGuanacasteUrl: "https://www.curiol.studio/linea-de-tiempo/golden-academy-santa-cruz",
  address: "Santa Bárbara de Santa Cruz, Guanacaste, Costa Rica",
};

export const INITIAL_CATEGORIES: string[] = [
  "Iniciación / Menores de U8 (U6-U8)",
  "Mini-Básquet (U8-U10)",
  "Infantil (U12-U14)",
  "Juvenil (U16-U18)",
  "Clínicas de Tecnificación & Tiro",
  "Intercantonal",
  "Eventos Especiales",
  "Presentación de Uniformes"
];

export const INITIAL_PLAYERS: Player[] = [
  {
    id: "ply-1",
    fullName: "Thiago Pérez Briceño",
    birthDate: "2018-04-12",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Jenny Briceño",
    guardianPhone: "62806989",
    guardianEmail: "jenny@gmail.com",
    photoUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&auto=format&fit=crop&q=80",
    jerseyNumber: 7,
    position: "Base / Armador",
    medicalNotes: "Ninguna",
    registrationDate: "2026-01-15",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-2",
    fullName: "Mateo Gutiérrez Monge",
    birthDate: "2016-08-22",
    category: "Mini-Básquet (U8-U10)",
    guardianName: "Carlos Gutiérrez",
    guardianPhone: "88882233",
    photoUrl: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&auto=format&fit=crop&q=80",
    jerseyNumber: 10,
    position: "Alero",
    registrationDate: "2026-02-01",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-3",
    fullName: "Valentina Vargas Leal",
    birthDate: "2013-11-05",
    category: "Infantil (U12-U14)",
    guardianName: "Marjorie Leal",
    guardianPhone: "87654321",
    photoUrl: "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=400&auto=format&fit=crop&q=80",
    jerseyNumber: 23,
    position: "Pívot",
    registrationDate: "2026-01-10",
    monthlyFee: 10000,
    paymentStatus: "pendiente",
    isActive: true,
  },
  {
    id: "ply-4",
    fullName: "Sebastián Zúñiga Arrieta",
    birthDate: "2009-03-14",
    category: "Juvenil (U16-U18)",
    guardianName: "Roberto Zúñiga",
    guardianPhone: "89991122",
    jerseyNumber: 30,
    position: "Escolta",
    registrationDate: "2026-01-20",
    monthlyFee: 10000,
    paymentStatus: "vencido",
    isActive: true,
  },
  {
    id: "ply-5",
    fullName: "Santiago Obando Ruiz",
    birthDate: "2017-06-18",
    category: "Iniciación / Menores de U8 (U6-U8)",
    guardianName: "Patricia Ruiz",
    guardianPhone: "83334455",
    jerseyNumber: 3,
    position: "Alero",
    registrationDate: "2026-02-10",
    monthlyFee: 10000,
    paymentStatus: "al_dia",
    isActive: true,
  },
  {
    id: "ply-test-alberto",
    fullName: "Mateo Bustos (Prueba Oficial)",
    birthDate: "2015-06-18",
    category: "Mini-Básquet (U8-U10)",
    guardianName: "Alberto Bustos",
    guardianPhone: "60602617",
    guardianEmail: "alberto.bustos.ortega@mep.go.cr",
    photoUrl: "/Hero_Basketball/1.jpg",
    jerseyNumber: 18,
    position: "Alero",
    registrationDate: "2026-01-10",
    monthlyFee: 10000,
    paymentStatus: "pendiente",
    isActive: true,
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: "pay-test-alberto",
    playerId: "ply-test-alberto",
    playerName: "Mateo Bustos (Prueba Oficial)",
    guardianName: "Alberto Bustos",
    guardianPhone: "60602617",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-1",
    playerId: "ply-1",
    playerName: "Thiago Pérez Briceño",
    guardianName: "Jenny Briceño",
    guardianPhone: "62806989",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    paymentDate: "2026-09-01",
    sinpeReference: "SINPE-998822",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-2",
    playerId: "ply-2",
    playerName: "Mateo Gutiérrez Monge",
    guardianName: "Carlos Gutiérrez",
    guardianPhone: "88882233",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pagado",
    paymentDate: "2026-09-02",
    sinpeReference: "SINPE-776655",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-3",
    playerId: "ply-3",
    playerName: "Valentina Vargas Leal",
    guardianName: "Marjorie Leal",
    guardianPhone: "87654321",
    month: "Septiembre",
    year: 2026,
    amount: 10000,
    status: "pendiente",
    dueDate: "2026-09-12",
  },
  {
    id: "pay-4",
    playerId: "ply-4",
    playerName: "Sebastián Zúñiga Arrieta",
    guardianName: "Roberto Zúñiga",
    guardianPhone: "89991122",
    month: "Agosto",
    year: 2026,
    amount: 10000,
    status: "atrasado",
    dueDate: "2026-08-12",
  },
];

// CARTELERA OFICIAL DE PARTIDOS DEL SÁBADO 5 DE SEPTIEMBRE EN LIBERIA
export const INITIAL_MATCHES: Match[] = [
  {
    id: "mtc-lib-2",
    category: "Mini-Básquet (U8-U10)",
    opponent: "Parajeles",
    matchDate: "2026-09-05",
    matchTime: "09:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles en categoría U10.",
  },
  {
    id: "mtc-lib-3",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles (U12 Mixto)",
    matchDate: "2026-09-05",
    matchTime: "10:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles (U12 Mixto).",
  },
  {
    id: "mtc-lib-4",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles (U14 Masc)",
    matchDate: "2026-09-05",
    matchTime: "11:00 AM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: true,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Parajeles (U14 Masculino).",
  },
  {
    id: "mtc-lib-5",
    category: "Infantil (U12-U14)",
    opponent: "Parajeles",
    matchDate: "2026-09-05",
    matchTime: "12:00 MD",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Santa Cruz vs Parajeles en U12 Mixto ⭐",
  },
  {
    id: "mtc-lib-6",
    category: "Infantil (U12-U14)",
    opponent: "Golden Sport Academy Santa Cruz (Fem)",
    matchDate: "2026-09-05",
    matchTime: "01:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Golden Sport Academy Santa Cruz (U12 Femenino) ⭐",
  },
  {
    id: "mtc-lib-7",
    category: "Infantil (U12-U14)",
    opponent: "Golden Sport Academy Santa Cruz (Mixto)",
    matchDate: "2026-09-05",
    matchTime: "02:00 PM",
    location: "Gimnasio Municipal de Liberia",
    locationUrl: "https://maps.google.com/?q=Gimnasio+Municipal+de+Liberia",
    isHome: false,
    status: "upcoming",
    summary: "Golden Sport Academy Liberia vs Golden Sport Academy Santa Cruz (U12 Mixto) ⭐",
  }
];

export const INITIAL_ALBUMS: GalleryAlbum[] = [
  {
    id: "alb-comunidad-liberia-2026",
    title: "Álbum Familiar • Gran Jornada de Liberia",
    eventDate: "2026-09-05",
    category: "Intercantonal",
    coverPhotoUrl: "/Hero_Basketball/1.jpg",
    createdBy: "Familias & Papás",
    albumType: "community",
    isLocked: false,
    isOpenForUploads: true,
  },
  {
    id: "alb-curiol-liberia-2026",
    title: "Galería Oficial Curiol Studio • Gran Jornada de Liberia 2026",
    eventDate: "2026-09-05",
    category: "Intercantonal",
    coverPhotoUrl: "/Hero_Basketball/2.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: false,
    isOpenForUploads: true,
  },
  {
    id: "alb-2",
    title: "Presentación del Uniforme Oficial",
    eventDate: "2026-08-22",
    category: "Presentación de Uniformes",
    coverPhotoUrl: "/photos/uniforme/GoldenAcademy_StaCruz_001.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: true,
    isOpenForUploads: false,
  },
  {
    id: "alb-3",
    title: "Clínicas de Tecnificación & Tiro",
    eventDate: "2026-08-20",
    category: "Clínicas de Tecnificación & Tiro",
    coverPhotoUrl: "/Hero_Basketball/2.jpg",
    createdBy: "Curiol Studio Oficial",
    albumType: "pro_studio",
    isLocked: true,
    isOpenForUploads: false,
  }
];

export const INITIAL_PHOTOS: GalleryPhoto[] = [
  // FOTOGRAFÍAS OFICIALES CURIOL STUDIO - PRESENTACIÓN DEL UNIFORME OFICIAL (16 FOTOS, alb-2)
  ...[
    "001", "002", "003", "004", "005", "006", "007", "008",
    "009", "010", "011", "012", "013", "014", "015", "016"
  ].map((num, idx) => ({
    id: `pht-uni-${num}`,
    photoUrl: `/photos/uniforme/GoldenAcademy_StaCruz_${num}.jpg`,
    title: `Presentación Oficial • Atleta #${num}`,
    caption: `Sesión fotográfica oficial de gala para la presentación de indumentaria deportiva de Golden Sport Academy Santa Cruz.`,
    category: "Presentación de Uniformes" as PlayerCategory,
    uploaderName: "Curiol Studio Oficial",
    uploaderRole: "staff" as const,
    photoType: "pro_studio" as const,
    albumId: "alb-2",
    eventDate: "2026-08-22",
    likesCount: 15 + (idx % 12),
    isApproved: true,
    uploadedAt: "2026-08-22",
    watermarkTag: "Curiol Studio Santa Cruz",
    priceDigital: 3500,
    pricePrint: 3500,
  }))
];

export const INITIAL_GALLERY_PHOTOS = INITIAL_PHOTOS;

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: "spn-1",
    name: "Curiol Studio",
    logoUrl: "/curiol-studio-logo.png",
    tier: "oro",
    websiteUrl: "https://www.curiol.studio",
    phone: "62806989",
    contactName: "Jenny Briceño",
    isActive: true,
  }
];

export const INITIAL_AUDIO_NOTES: AudioNote[] = [
  {
    id: "aud-1",
    title: "Coordinación logística para la jornada en Liberia",
    transcript: "Organizar la salida de los atletas a las 6:30 AM desde Santa Bárbara. Llevar hidratación y los uniformes dorados oficiales.",
    summaryIA: "Salida 6:30 AM hacia el Gimnasio Municipal de Liberia. Uniforme de gala y botiquín listo.",
    actionItems: [
      "Confirmar transporte de los niños",
      "Revisión de balones y uniformes",
      "Puntualidad en el primer partido de las 8:00 AM"
    ],
    category: "directiva",
    recordedAt: "2026-09-03",
    author: "Coach Lenny Monge",
  }
];
